<?php

return [
    'products' => [
        'table' => 'products',
        'write_roles' => ['owner', 'admin'],
        'searchable' => ['name', 'sku', 'category'],
        'default_sort' => 'name',
        'date_field' => 'created_at',
        'fields' => [
            'name' => ['type' => 'string', 'required' => true],
            'sku' => ['type' => 'string'],
            'category' => ['type' => 'string'],
            'cost_cents' => ['type' => 'unsigned_integer'],
            'price_cents' => ['type' => 'unsigned_integer'],
            'stock_quantity' => ['type' => 'integer'],
            'min_stock_quantity' => ['type' => 'integer'],
            'is_active' => ['type' => 'boolean'],
            'metadata' => ['type' => 'json'],
        ],
    ],
    'suppliers' => [
        'table' => 'suppliers',
        'write_roles' => ['owner', 'admin'],
        'searchable' => ['name', 'contact_name', 'email', 'document'],
        'default_sort' => 'name',
        'date_field' => 'created_at',
        'fields' => [
            'name' => ['type' => 'string', 'required' => true],
            'contact_name' => ['type' => 'string'],
            'phone' => ['type' => 'string'],
            'email' => ['type' => 'email'],
            'document' => ['type' => 'string'],
            'status' => ['type' => 'string', 'enum' => ['active', 'inactive']],
            'notes' => ['type' => 'text'],
            'metadata' => ['type' => 'json'],
        ],
    ],
    'stock-movements' => [
        'table' => 'stock_movements',
        'write_roles' => ['owner', 'admin', 'reception'],
        'searchable' => ['type', 'reason', 'reference'],
        'default_sort' => 'moved_at',
        'date_field' => 'moved_at',
        'auto_user_field' => 'created_by_user_id',
        'scoped_relations' => [
            'product_id' => 'products',
            'supplier_id' => 'suppliers',
        ],
        'fields' => [
            'product_id' => ['type' => 'unsigned_integer', 'required' => true],
            'supplier_id' => ['type' => 'unsigned_integer'],
            'type' => ['type' => 'string', 'required' => true, 'enum' => ['entry', 'exit', 'adjustment']],
            'quantity' => ['type' => 'integer', 'required' => true],
            'unit_cost_cents' => ['type' => 'unsigned_integer'],
            'total_cost_cents' => ['type' => 'unsigned_integer'],
            'reason' => ['type' => 'string'],
            'reference' => ['type' => 'string'],
            'moved_at' => ['type' => 'datetime'],
            'metadata' => ['type' => 'json'],
        ],
    ],
    'stock-alerts' => [
        'table' => 'stock_alerts',
        'write_roles' => ['owner', 'admin'],
        'searchable' => ['message', 'level', 'status'],
        'default_sort' => 'created_at',
        'date_field' => 'created_at',
        'scoped_relations' => [
            'product_id' => 'products',
        ],
        'fields' => [
            'product_id' => ['type' => 'unsigned_integer'],
            'level' => ['type' => 'string', 'enum' => ['info', 'warning', 'critical']],
            'status' => ['type' => 'string', 'enum' => ['open', 'acknowledged', 'resolved']],
            'message' => ['type' => 'text', 'required' => true],
            'resolved_at' => ['type' => 'datetime'],
            'metadata' => ['type' => 'json'],
        ],
    ],
    'expenses' => [
        'table' => 'expenses',
        'write_roles' => ['owner', 'admin', 'reception'],
        'searchable' => ['name', 'category', 'status', 'payment_method'],
        'default_sort' => 'due_at',
        'date_field' => 'due_at',
        'fields' => [
            'name' => ['type' => 'string', 'required' => true],
            'category' => ['type' => 'string', 'required' => true],
            'description' => ['type' => 'text'],
            'amount_cents' => ['type' => 'unsigned_integer', 'required' => true],
            'status' => ['type' => 'string', 'enum' => ['pending', 'paid', 'cancelled']],
            'due_at' => ['type' => 'datetime'],
            'paid_at' => ['type' => 'datetime'],
            'payment_method' => ['type' => 'string'],
            'recurrence' => ['type' => 'string'],
            'metadata' => ['type' => 'json'],
        ],
    ],
    'payouts' => [
        'table' => 'payouts',
        'write_roles' => ['owner', 'admin'],
        'searchable' => ['status', 'notes'],
        'default_sort' => 'period_end',
        'date_field' => 'period_end',
        'auto_user_field' => 'generated_by_user_id',
        'fields' => [
            'period_start' => ['type' => 'date', 'required' => true],
            'period_end' => ['type' => 'date', 'required' => true],
            'status' => ['type' => 'string', 'enum' => ['pending', 'processing', 'paid', 'cancelled']],
            'gross_cents' => ['type' => 'unsigned_integer'],
            'discount_cents' => ['type' => 'unsigned_integer'],
            'net_cents' => ['type' => 'unsigned_integer'],
            'paid_at' => ['type' => 'datetime'],
            'notes' => ['type' => 'text'],
            'metadata' => ['type' => 'json'],
        ],
    ],
    'commissions' => [
        'table' => 'commissions',
        'write_roles' => ['owner', 'admin'],
        'searchable' => ['status', 'reference_type'],
        'default_sort' => 'created_at',
        'date_field' => 'created_at',
        'scoped_relations' => [
            'membership_id' => 'barbershop_memberships',
        ],
        'fields' => [
            'membership_id' => ['type' => 'unsigned_integer'],
            'reference_type' => ['type' => 'string'],
            'reference_id' => ['type' => 'unsigned_integer'],
            'base_amount_cents' => ['type' => 'unsigned_integer', 'required' => true],
            'rate' => ['type' => 'decimal', 'required' => true],
            'amount_cents' => ['type' => 'unsigned_integer', 'required' => true],
            'status' => ['type' => 'string', 'enum' => ['pending', 'settled', 'cancelled']],
            'settled_at' => ['type' => 'datetime'],
            'metadata' => ['type' => 'json'],
        ],
    ],
    'loyalty-programs' => [
        'table' => 'loyalty_programs',
        'write_roles' => ['owner', 'admin'],
        'searchable' => ['name', 'description'],
        'default_sort' => 'name',
        'date_field' => 'created_at',
        'fields' => [
            'name' => ['type' => 'string', 'required' => true],
            'description' => ['type' => 'text'],
            'points_per_currency_unit' => ['type' => 'unsigned_integer'],
            'is_active' => ['type' => 'boolean'],
            'starts_at' => ['type' => 'datetime'],
            'ends_at' => ['type' => 'datetime'],
            'settings' => ['type' => 'json'],
        ],
    ],
    'points' => [
        'table' => 'points_ledger',
        'write_roles' => ['owner', 'admin', 'reception', 'barber'],
        'searchable' => ['reason', 'reference_type'],
        'default_sort' => 'created_at',
        'date_field' => 'created_at',
        'scoped_relations' => [
            'customer_id' => 'customers',
            'loyalty_program_id' => 'loyalty_programs',
        ],
        'fields' => [
            'customer_id' => ['type' => 'unsigned_integer', 'required' => true],
            'loyalty_program_id' => ['type' => 'unsigned_integer'],
            'change_points' => ['type' => 'integer', 'required' => true],
            'reason' => ['type' => 'string', 'required' => true],
            'reference_type' => ['type' => 'string'],
            'reference_id' => ['type' => 'unsigned_integer'],
            'expires_at' => ['type' => 'datetime'],
            'metadata' => ['type' => 'json'],
        ],
    ],
    'rewards' => [
        'table' => 'rewards',
        'write_roles' => ['owner', 'admin'],
        'searchable' => ['name', 'description'],
        'default_sort' => 'points_cost',
        'date_field' => 'created_at',
        'scoped_relations' => [
            'loyalty_program_id' => 'loyalty_programs',
        ],
        'fields' => [
            'loyalty_program_id' => ['type' => 'unsigned_integer'],
            'name' => ['type' => 'string', 'required' => true],
            'description' => ['type' => 'text'],
            'points_cost' => ['type' => 'unsigned_integer', 'required' => true],
            'stock_quantity' => ['type' => 'integer'],
            'is_active' => ['type' => 'boolean'],
            'metadata' => ['type' => 'json'],
        ],
    ],
    'redemptions' => [
        'table' => 'redemptions',
        'write_roles' => ['owner', 'admin', 'reception', 'barber'],
        'searchable' => ['status'],
        'default_sort' => 'created_at',
        'date_field' => 'created_at',
        'scoped_relations' => [
            'customer_id' => 'customers',
            'reward_id' => 'rewards',
        ],
        'fields' => [
            'customer_id' => ['type' => 'unsigned_integer', 'required' => true],
            'reward_id' => ['type' => 'unsigned_integer', 'required' => true],
            'points_spent' => ['type' => 'unsigned_integer', 'required' => true],
            'status' => ['type' => 'string', 'enum' => ['requested', 'approved', 'cancelled', 'completed']],
            'redeemed_at' => ['type' => 'datetime'],
            'metadata' => ['type' => 'json'],
        ],
    ],
    'coupons' => [
        'table' => 'coupons',
        'write_roles' => ['owner', 'admin'],
        'searchable' => ['name', 'code', 'status'],
        'default_sort' => 'created_at',
        'date_field' => 'created_at',
        'fields' => [
            'code' => ['type' => 'string', 'required' => true],
            'name' => ['type' => 'string', 'required' => true],
            'description' => ['type' => 'text'],
            'discount_type' => ['type' => 'string', 'required' => true, 'enum' => ['fixed', 'percent']],
            'discount_value' => ['type' => 'unsigned_integer', 'required' => true],
            'max_redemptions' => ['type' => 'unsigned_integer'],
            'redeemed_count' => ['type' => 'unsigned_integer'],
            'starts_at' => ['type' => 'datetime'],
            'ends_at' => ['type' => 'datetime'],
            'is_active' => ['type' => 'boolean'],
            'metadata' => ['type' => 'json'],
        ],
    ],
    'campaigns' => [
        'table' => 'campaigns',
        'write_roles' => ['owner', 'admin'],
        'searchable' => ['name', 'channel', 'status'],
        'default_sort' => 'created_at',
        'date_field' => 'created_at',
        'fields' => [
            'name' => ['type' => 'string', 'required' => true],
            'channel' => ['type' => 'string', 'required' => true, 'enum' => ['whatsapp', 'email', 'sms', 'push']],
            'status' => ['type' => 'string', 'enum' => ['draft', 'scheduled', 'running', 'completed', 'cancelled']],
            'audience_filter' => ['type' => 'json'],
            'message_template' => ['type' => 'text'],
            'starts_at' => ['type' => 'datetime'],
            'ends_at' => ['type' => 'datetime'],
            'metadata' => ['type' => 'json'],
        ],
    ],
    'campaign-runs' => [
        'table' => 'campaign_runs',
        'write_roles' => ['owner', 'admin'],
        'searchable' => ['status'],
        'default_sort' => 'scheduled_at',
        'date_field' => 'scheduled_at',
        'scoped_relations' => [
            'campaign_id' => 'campaigns',
        ],
        'fields' => [
            'campaign_id' => ['type' => 'unsigned_integer', 'required' => true],
            'status' => ['type' => 'string', 'enum' => ['queued', 'running', 'completed', 'failed', 'cancelled']],
            'scheduled_at' => ['type' => 'datetime'],
            'started_at' => ['type' => 'datetime'],
            'finished_at' => ['type' => 'datetime'],
            'metrics' => ['type' => 'json'],
            'logs' => ['type' => 'text'],
            'metadata' => ['type' => 'json'],
        ],
    ],
    'birthdays' => [
        'table' => 'birthday_automations',
        'write_roles' => ['owner', 'admin'],
        'searchable' => ['name', 'channel', 'status'],
        'default_sort' => 'created_at',
        'date_field' => 'created_at',
        'fields' => [
            'name' => ['type' => 'string', 'required' => true],
            'days_before' => ['type' => 'integer'],
            'channel' => ['type' => 'string', 'enum' => ['whatsapp', 'email', 'sms', 'push']],
            'status' => ['type' => 'string', 'enum' => ['active', 'paused']],
            'template' => ['type' => 'text'],
            'is_active' => ['type' => 'boolean'],
            'metadata' => ['type' => 'json'],
        ],
    ],
    'support/tickets' => [
        'table' => 'support_tickets',
        'write_roles' => ['owner', 'admin', 'reception'],
        'searchable' => ['title', 'status', 'priority'],
        'default_sort' => 'created_at',
        'date_field' => 'created_at',
        'scoped_relations' => [
            'customer_id' => 'customers',
            'assigned_user_id' => [
                'table' => 'barbershop_memberships',
                'column' => 'user_id',
            ],
        ],
        'fields' => [
            'customer_id' => ['type' => 'unsigned_integer'],
            'title' => ['type' => 'string', 'required' => true],
            'description' => ['type' => 'text', 'required' => true],
            'status' => ['type' => 'string', 'enum' => ['open', 'in_progress', 'waiting_customer', 'closed']],
            'priority' => ['type' => 'string', 'enum' => ['low', 'medium', 'high', 'urgent']],
            'assigned_user_id' => ['type' => 'unsigned_integer'],
            'closed_at' => ['type' => 'datetime'],
            'metadata' => ['type' => 'json'],
        ],
    ],
    'support/messages' => [
        'table' => 'ticket_messages',
        'write_roles' => ['owner', 'admin', 'reception', 'barber'],
        'searchable' => ['message'],
        'default_sort' => 'created_at',
        'date_field' => 'created_at',
        'scoped_relations' => [
            'ticket_id' => 'support_tickets',
            'sender_user_id' => [
                'table' => 'barbershop_memberships',
                'column' => 'user_id',
            ],
            'sender_customer_id' => 'customers',
        ],
        'fields' => [
            'ticket_id' => ['type' => 'unsigned_integer', 'required' => true],
            'sender_user_id' => ['type' => 'unsigned_integer'],
            'sender_customer_id' => ['type' => 'unsigned_integer'],
            'message' => ['type' => 'text', 'required' => true],
            'attachments' => ['type' => 'json'],
            'metadata' => ['type' => 'json'],
        ],
    ],
    'faq' => [
        'table' => 'faq_articles',
        'write_roles' => ['owner', 'admin'],
        'searchable' => ['title', 'category', 'status'],
        'default_sort' => 'sort_order',
        'date_field' => 'created_at',
        'fields' => [
            'title' => ['type' => 'string', 'required' => true],
            'slug' => ['type' => 'string', 'required' => true],
            'content' => ['type' => 'text', 'required' => true],
            'category' => ['type' => 'string'],
            'status' => ['type' => 'string', 'enum' => ['draft', 'published', 'archived']],
            'sort_order' => ['type' => 'integer'],
            'metadata' => ['type' => 'json'],
        ],
    ],
    'notifications' => [
        'table' => 'notifications',
        'write_roles' => ['owner', 'admin', 'reception'],
        'searchable' => ['type', 'title', 'status'],
        'default_sort' => 'created_at',
        'date_field' => 'created_at',
        'scoped_relations' => [
            'recipient_user_id' => [
                'table' => 'barbershop_memberships',
                'column' => 'user_id',
            ],
            'recipient_customer_id' => 'customers',
        ],
        'fields' => [
            'recipient_user_id' => ['type' => 'unsigned_integer'],
            'recipient_customer_id' => ['type' => 'unsigned_integer'],
            'type' => ['type' => 'string', 'required' => true],
            'title' => ['type' => 'string', 'required' => true],
            'body' => ['type' => 'text', 'required' => true],
            'status' => ['type' => 'string', 'enum' => ['queued', 'sent', 'failed', 'read']],
            'read_at' => ['type' => 'datetime'],
            'sent_at' => ['type' => 'datetime'],
            'payload' => ['type' => 'json'],
            'metadata' => ['type' => 'json'],
        ],
    ],
    'templates' => [
        'table' => 'notification_templates',
        'write_roles' => ['owner', 'admin'],
        'searchable' => ['key', 'channel'],
        'default_sort' => 'key',
        'date_field' => 'created_at',
        'fields' => [
            'key' => ['type' => 'string', 'required' => true],
            'channel' => ['type' => 'string', 'required' => true, 'enum' => ['whatsapp', 'email', 'sms', 'push']],
            'title_template' => ['type' => 'string'],
            'body_template' => ['type' => 'text', 'required' => true],
            'is_active' => ['type' => 'boolean'],
            'metadata' => ['type' => 'json'],
        ],
    ],
    'dispatches' => [
        'table' => 'notification_dispatches',
        'write_roles' => ['owner', 'admin', 'reception'],
        'searchable' => ['channel', 'status', 'provider'],
        'default_sort' => 'created_at',
        'date_field' => 'created_at',
        'scoped_relations' => [
            'notification_id' => 'notifications',
        ],
        'fields' => [
            'notification_id' => ['type' => 'unsigned_integer'],
            'channel' => ['type' => 'string', 'required' => true],
            'status' => ['type' => 'string', 'enum' => ['queued', 'sent', 'failed', 'cancelled']],
            'provider' => ['type' => 'string'],
            'provider_reference' => ['type' => 'string'],
            'error_message' => ['type' => 'text'],
            'last_attempt_at' => ['type' => 'datetime'],
            'attempt_count' => ['type' => 'unsigned_integer'],
            'metadata' => ['type' => 'json'],
        ],
    ],
    'security/events' => [
        'table' => 'security_events',
        'write_roles' => ['owner', 'admin'],
        'searchable' => ['event_type', 'severity', 'ip_address'],
        'default_sort' => 'occurred_at',
        'date_field' => 'occurred_at',
        'scoped_relations' => [
            'user_id' => [
                'table' => 'barbershop_memberships',
                'column' => 'user_id',
            ],
        ],
        'fields' => [
            'user_id' => ['type' => 'unsigned_integer'],
            'event_type' => ['type' => 'string', 'required' => true],
            'severity' => ['type' => 'string', 'enum' => ['info', 'warning', 'critical']],
            'ip_address' => ['type' => 'string'],
            'user_agent' => ['type' => 'text'],
            'context' => ['type' => 'json'],
            'occurred_at' => ['type' => 'datetime'],
            'metadata' => ['type' => 'json'],
        ],
    ],
    'audit/logs' => [
        'table' => 'audit_logs',
        'write_roles' => ['owner', 'admin'],
        'searchable' => ['action', 'entity_type', 'ip_address'],
        'default_sort' => 'occurred_at',
        'date_field' => 'occurred_at',
        'scoped_relations' => [
            'user_id' => [
                'table' => 'barbershop_memberships',
                'column' => 'user_id',
            ],
        ],
        'fields' => [
            'user_id' => ['type' => 'unsigned_integer'],
            'action' => ['type' => 'string', 'required' => true],
            'entity_type' => ['type' => 'string'],
            'entity_id' => ['type' => 'unsigned_integer'],
            'before_state' => ['type' => 'json'],
            'after_state' => ['type' => 'json'],
            'ip_address' => ['type' => 'string'],
            'occurred_at' => ['type' => 'datetime'],
            'metadata' => ['type' => 'json'],
        ],
    ],
    'webhooks/logs' => [
        'table' => 'webhook_deliveries',
        'write_roles' => ['owner', 'admin'],
        'searchable' => ['source', 'event_type', 'status', 'url'],
        'default_sort' => 'created_at',
        'date_field' => 'created_at',
        'fields' => [
            'source' => ['type' => 'string', 'required' => true],
            'event_type' => ['type' => 'string', 'required' => true],
            'status' => ['type' => 'string', 'enum' => ['pending', 'sent', 'failed', 'retrying']],
            'url' => ['type' => 'string', 'required' => true],
            'payload' => ['type' => 'json', 'required' => true],
            'response_code' => ['type' => 'integer'],
            'response_body' => ['type' => 'text'],
            'last_attempt_at' => ['type' => 'datetime'],
            'attempt_count' => ['type' => 'unsigned_integer'],
            'metadata' => ['type' => 'json'],
        ],
    ],
    'analytics/snapshots' => [
        'table' => 'analytics_snapshots',
        'write_roles' => ['owner', 'admin'],
        'searchable' => ['scope'],
        'default_sort' => 'snapshot_date',
        'date_field' => 'snapshot_date',
        'fields' => [
            'scope' => ['type' => 'string'],
            'snapshot_date' => ['type' => 'date', 'required' => true],
            'metrics' => ['type' => 'json', 'required' => true],
            'metadata' => ['type' => 'json'],
        ],
    ],
];
