/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#516900",
        "error-container": "#b92902",
        "surface": "#0e0e0e",
        "surface-variant": "#262626",
        "on-primary-fixed": "#394b00",
        "on-primary-container": "#485e00",
        "secondary": "#e5e2e1",
        "on-background": "#ffffff",
        "on-surface": "#ffffff",
        "primary-container": "#c7fe00",
        "surface-container-low": "#131313",
        "surface-container-lowest": "#000000",
        "surface-tint": "#f3ffcc",
        "on-secondary-container": "#d2d0cf",
        "primary-dim": "#bbef00",
        "on-tertiary-fixed-variant": "#6e6d6d",
        "background": "#0e0e0e",
        "secondary-container": "#474746",
        "on-secondary-fixed": "#403f3f",
        "primary-fixed-dim": "#bbef00",
        "tertiary-fixed": "#ffffff",
        "on-tertiary-container": "#575756",
        "on-secondary": "#525151",
        "surface-dim": "#0e0e0e",
        "surface-container-highest": "#262626",
        "tertiary-dim": "#edeaea",
        "on-tertiary": "#5f5f5f",
        "inverse-surface": "#fcf9f8",
        "on-surface-variant": "#adaaaa",
        "secondary-fixed-dim": "#d6d4d3",
        "primary": "#f3ffcc",
        "on-secondary-fixed-variant": "#5c5b5b",
        "on-error": "#450900",
        "surface-container": "#1a1919",
        "surface-bright": "#2c2c2c",
        "outline-variant": "#484847",
        "surface-container-high": "#201f1f",
        "on-primary": "#4f6700",
        "on-error-container": "#ffd2c8",
        "primary-fixed": "#c7fe00",
        "inverse-primary": "#4f6700",
        "tertiary-fixed-dim": "#f3f0f0",
        "secondary-fixed": "#e5e2e1",
        "error": "#ff7351",
        "tertiary": "#fbf9f8",
        "on-tertiary-fixed": "#505050",
        "error-dim": "#d53d18",
        "inverse-on-surface": "#565555",
        "tertiary-container": "#edeaea",
        "secondary-dim": "#d6d4d3",
        "outline": "#767575"
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Plus Jakarta Sans", "sans-serif"],
      },
    },
  },
  plugins: [],
}
