begin;

create table if not exists public.migrations (
  id integer generated by default as identity primary key,
  migration varchar(255) not null,
  batch integer not null
);

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  email_verified_at timestamptz null,
  password text not null,
  remember_token text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.password_reset_tokens (
  email varchar(255) primary key,
  token varchar(255) not null,
  created_at timestamptz null
);

create table if not exists public.sessions (
  id varchar(255) primary key,
  user_id bigint null,
  ip_address varchar(45) null,
  user_agent text null,
  payload text not null,
  last_activity integer not null
);

create index if not exists sessions_user_id_index on public.sessions (user_id);
create index if not exists sessions_last_activity_index on public.sessions (last_activity);

create table if not exists public.barbershops (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  phone text null,
  email text null,
  timezone text not null default 'America/Cuiaba',
  currency char(3) not null default 'BRL',
  address jsonb null,
  settings jsonb null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  barbershop_id bigint not null references public.barbershops(id) on delete cascade,
  name text not null,
  phone text null,
  email text null,
  birthday date null,
  notes text null,
  loyalty_points integer not null default 0,
  total_visits integer not null default 0,
  last_visit_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists customers_barbershop_name_idx on public.customers (barbershop_id, name);
create index if not exists customers_barbershop_phone_idx on public.customers (barbershop_id, phone);
create index if not exists customers_barbershop_email_idx on public.customers (barbershop_id, email);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  barbershop_id bigint not null references public.barbershops(id) on delete cascade,
  name text not null,
  slug text not null,
  description text null,
  duration_minutes integer not null,
  price_cents integer not null,
  is_active boolean not null default true,
  sort_order smallint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint services_barbershop_slug_unique unique (barbershop_id, slug)
);

create index if not exists services_barbershop_active_idx on public.services (barbershop_id, is_active);

create table if not exists public.cache (
  key varchar(255) primary key,
  value text not null,
  expiration bigint not null
);

create index if not exists cache_expiration_index on public.cache (expiration);

create table if not exists public.cache_locks (
  key varchar(255) primary key,
  owner varchar(255) not null,
  expiration bigint not null
);

create index if not exists cache_locks_expiration_index on public.cache_locks (expiration);

create table if not exists public.barbershop_memberships (
  id bigint generated by default as identity primary key,
  barbershop_id bigint not null references public.barbershops(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  role text not null default 'barber',
  commission_rate numeric(5,2) null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint barbershop_memberships_shop_user_unique unique (barbershop_id, user_id)
);

create index if not exists barbershop_memberships_barbershop_role_idx on public.barbershop_memberships (barbershop_id, role);

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  barbershop_id bigint not null references public.barbershops(id) on delete cascade,
  customer_id bigint null references public.customers(id) on delete set null,
  barber_user_id bigint null references public.users(id) on delete set null,
  service_id bigint null references public.services(id) on delete set null,
  scheduled_start_at timestamptz not null,
  scheduled_end_at timestamptz null,
  status text not null default 'scheduled',
  channel text null,
  notes text null,
  created_by_user_id bigint null references public.users(id) on delete set null,
  cancelled_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists appointments_barbershop_start_idx on public.appointments (barbershop_id, scheduled_start_at);
create index if not exists appointments_barber_start_idx on public.appointments (barber_user_id, scheduled_start_at);
create index if not exists appointments_customer_start_idx on public.appointments (customer_id, scheduled_start_at);
create index if not exists appointments_barbershop_status_idx on public.appointments (barbershop_id, status);

create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  queue varchar(255) not null,
  payload text not null,
  attempts smallint not null,
  reserved_at integer null,
  available_at integer not null,
  created_at integer not null
);

create index if not exists jobs_queue_index on public.jobs (queue);

create table if not exists public.job_batches (
  id varchar(255) primary key,
  name varchar(255) not null,
  total_jobs integer not null,
  pending_jobs integer not null,
  failed_jobs integer not null,
  failed_job_ids text not null,
  options text null,
  cancelled_at integer null,
  created_at integer not null,
  finished_at integer null
);

create table if not exists public.failed_jobs (
  id bigint generated by default as identity primary key,
  uuid varchar(255) not null unique,
  connection text not null,
  queue text not null,
  payload text not null,
  exception text not null,
  failed_at timestamptz not null default now()
);

create table if not exists public.charges (
  id bigint generated by default as identity primary key,
  barbershop_id bigint not null references public.barbershops(id) on delete cascade,
  customer_id bigint null references public.customers(id) on delete set null,
  appointment_id bigint null references public.appointments(id) on delete set null unique,
  status text not null default 'pending',
  subtotal_cents integer not null default 0,
  discount_cents integer not null default 0,
  total_cents integer not null default 0,
  payment_method text null,
  gateway text null,
  gateway_reference text null,
  due_at timestamptz null,
  paid_at timestamptz null,
  metadata jsonb null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists charges_barbershop_status_idx on public.charges (barbershop_id, status);
create index if not exists charges_gateway_reference_idx on public.charges (gateway, gateway_reference);

create table if not exists public.charge_items (
  id bigint generated by default as identity primary key,
  charge_id bigint not null references public.charges(id) on delete cascade,
  service_id bigint null references public.services(id) on delete set null,
  description text not null,
  quantity integer not null default 1,
  unit_price_cents integer not null,
  total_price_cents integer not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.services enable row level security;
drop policy if exists services_public_read on public.services;
create policy services_public_read
on public.services
for select
to anon, authenticated
using (is_active = true);

grant usage on schema public to anon, authenticated;
grant select on public.services to anon, authenticated;

insert into public.users (name, email, password, updated_at)
values (
  'Barbeiro Demo',
  'barbeiro.demo@barbeariacabral.com',
  '$2y$12$demo-placeholder-hash',
  now()
)
on conflict (email) do update
  set name = excluded.name,
      password = excluded.password,
      updated_at = now();

insert into public.barbershops (name, slug, phone, email, timezone, currency, address, settings, is_active, updated_at)
values (
  'Barbearia Cabral',
  'barbearia-cabral',
  '(65) 99999-0000',
  'contato@barbeariacabral.com',
  'America/Cuiaba',
  'BRL',
  jsonb_build_object(
    'street', 'Av. Principal, 100',
    'district', 'Centro',
    'city', 'Cuiaba',
    'state', 'MT'
  ),
  jsonb_build_object(
    'booking_interval_minutes', 30,
    'allow_walk_ins', true,
    'public_catalog', true
  ),
  true,
  now()
)
on conflict (slug) do update
  set name = excluded.name,
      phone = excluded.phone,
      email = excluded.email,
      timezone = excluded.timezone,
      currency = excluded.currency,
      address = excluded.address,
      settings = excluded.settings,
      is_active = excluded.is_active,
      updated_at = now();

insert into public.services (barbershop_id, name, slug, description, duration_minutes, price_cents, is_active, sort_order, updated_at)
values
  ((select id from public.barbershops where slug = 'barbearia-cabral'), 'Corte Tradicional', 'corte-tradicional', 'Corte masculino classico com acabamento.', 45, 4500, true, 10, now()),
  ((select id from public.barbershops where slug = 'barbearia-cabral'), 'Barba Completa', 'barba-completa', 'Modelagem e toalha quente para barba.', 30, 3000, true, 20, now()),
  ((select id from public.barbershops where slug = 'barbearia-cabral'), 'Combo Corte + Barba', 'combo-corte-barba', 'Pacote completo para atendimento premium.', 75, 7000, true, 30, now())
on conflict (barbershop_id, slug) do update
  set name = excluded.name,
      description = excluded.description,
      duration_minutes = excluded.duration_minutes,
      price_cents = excluded.price_cents,
      is_active = excluded.is_active,
      sort_order = excluded.sort_order,
      updated_at = now();

insert into public.customers (
  barbershop_id,
  name,
  phone,
  email,
  birthday,
  notes,
  loyalty_points,
  total_visits,
  last_visit_at,
  updated_at
)
select
  b.id,
  'Cliente Demo',
  '(65) 99999-1111',
  'cliente.demo@barbeariacabral.com',
  date '1994-06-15',
  'Cliente seed para smoke tests do catalogo.',
  120,
  6,
  now(),
  now()
from public.barbershops b
where b.slug = 'barbearia-cabral'
  and not exists (
    select 1
    from public.customers c
    where c.barbershop_id = b.id
      and c.email = 'cliente.demo@barbeariacabral.com'
  );

insert into public.barbershop_memberships (barbershop_id, user_id, role, commission_rate, is_active, updated_at)
select
  b.id,
  u.id,
  'barber',
  45.00,
  true,
  now()
from public.barbershops b
join public.users u on u.email = 'barbeiro.demo@barbeariacabral.com'
where b.slug = 'barbearia-cabral'
on conflict (barbershop_id, user_id) do update
  set role = excluded.role,
      commission_rate = excluded.commission_rate,
      is_active = excluded.is_active,
      updated_at = now();

insert into public.appointments (
  barbershop_id,
  customer_id,
  barber_user_id,
  service_id,
  scheduled_start_at,
  scheduled_end_at,
  status,
  channel,
  notes,
  created_by_user_id,
  updated_at
)
select
  b.id,
  c.id,
  u.id,
  s.id,
  timestamptz '2026-04-03 14:00:00+00',
  timestamptz '2026-04-03 14:45:00+00',
  'completed',
  'manual',
  'Atendimento demo para validar agenda e cobranca.',
  u.id,
  now()
from public.barbershops b
join public.customers c on c.barbershop_id = b.id and c.email = 'cliente.demo@barbeariacabral.com'
join public.users u on u.email = 'barbeiro.demo@barbeariacabral.com'
join public.services s on s.barbershop_id = b.id and s.slug = 'corte-tradicional'
where b.slug = 'barbearia-cabral'
  and not exists (
    select 1
    from public.appointments a
    where a.barbershop_id = b.id
      and a.customer_id = c.id
      and a.scheduled_start_at = timestamptz '2026-04-03 14:00:00+00'
  );

insert into public.charges (
  barbershop_id,
  customer_id,
  appointment_id,
  status,
  subtotal_cents,
  discount_cents,
  total_cents,
  payment_method,
  gateway,
  gateway_reference,
  due_at,
  paid_at,
  metadata,
  updated_at
)
select
  b.id,
  c.id,
  a.id,
  'paid',
  4500,
  0,
  4500,
  'cash',
  'manual',
  'demo-charge-001',
  timestamptz '2026-04-03 15:00:00+00',
  timestamptz '2026-04-03 14:50:00+00',
  jsonb_build_object('source', 'sql-bootstrap'),
  now()
from public.barbershops b
join public.customers c on c.barbershop_id = b.id and c.email = 'cliente.demo@barbeariacabral.com'
join public.appointments a on a.barbershop_id = b.id and a.customer_id = c.id and a.scheduled_start_at = timestamptz '2026-04-03 14:00:00+00'
where b.slug = 'barbearia-cabral'
  and not exists (
    select 1
    from public.charges ch
    where ch.appointment_id = a.id
  );

insert into public.charge_items (
  charge_id,
  service_id,
  description,
  quantity,
  unit_price_cents,
  total_price_cents,
  updated_at
)
select
  ch.id,
  s.id,
  'Corte Tradicional',
  1,
  4500,
  4500,
  now()
from public.charges ch
join public.appointments a on a.id = ch.appointment_id
join public.barbershops b on b.id = a.barbershop_id and b.slug = 'barbearia-cabral'
join public.services s on s.barbershop_id = b.id and s.slug = 'corte-tradicional'
where not exists (
  select 1
  from public.charge_items ci
  where ci.charge_id = ch.id
    and ci.service_id = s.id
    and ci.description = 'Corte Tradicional'
);

insert into public.migrations (migration, batch)
values
  ('0001_01_01_000000_create_users_table', 1),
  ('0001_01_01_000001_create_cache_table', 1),
  ('0001_01_01_000002_create_jobs_table', 1),
  ('2026_04_03_000100_create_barbershop_core_tables', 1),
  ('2026_04_03_000200_create_appointments_and_billing_tables', 1),
  ('2026_04_03_000300_enable_public_service_catalog_policy', 1)
on conflict do nothing;

commit;
